### ISSUE TITLE
Four improvement requests for “3.Bayesian network meta-analysis “

### ISSUE THREAD

**Issue by chubukeita** [CRSU-Apps/MetaInsight#79]
1. I would like you to add a function to download the analysis results of MetaInsight in a batch as a Zip file.
2. The current version of MetaInsight is not reproducible, so I would like to be able to specify the Seed.
3. When downloading the " Ranking Results " of "Ranking panel for all studies” in the “3c. Ranking Panel” , Please improve so that SVG files can also be downloaded.
4. I would like the lower and upper limits of 95 % CrI in Forest Plot to be adjusted automatically so that the entire 95 % CrI fits in the plot.

**Comment by BalancedmonkeY** [comment]
Hi @chubukeita
Thank you for sharing your thoughts for improving the Bayesian tab of MetaInsight. We have split your requests into the following separate GitHub Issues:

1. This is now issue #80. However, due to other features currently being developed being of a higher priority, we cannot specify when this feature will be worked on.
2. Issue #76 already talks about this, and this is something we are working on currently. Note that I have added a comment to the existing issue about the user having the option to change the seed if they wish.
3. This is now issue #81 and will likely extend to other downloadable images across MetaInsight. As with point 1, due to other features currently being developed being of a higher priority, we cannot specify when this feature will be worked on.
4. This is now issue #82. For some context, in previous versions of MetaInsight, the axes of the forest plots would automatically adjust to fit all CrIs. However, for some analyses, where there was a spuriously large 95% CrI, this would 'dwarf' the remaining comparisons making the plot uninterpretable. To resolve this, the option for the user to adjust the axis was added. The new issue will work on setting different default values to the input.  As with points 1 and 3, due to other features currently being developed being of a higher priority, we cannot specify when this feature will be worked on.
